# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: docs/conf.py

build:
  image: testing

# TODO: maybe don't require a full install of scipy etc. to build docs?
python:
   version: 3.9
   install:
   - requirements: requirements.txt
   - requirements: requirements-dev.txt
