name: encomp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - scipy
  - jupyter
  - CoolProp
  - pip:
      - -r file:requirements.txt
      - -r file:requirements-dev.txt
