name: encomp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pydantic
  - pytest
  - scipy
  - jupyter
  - CoolProp
  - wntr
  - pint
  - fluids
  - thermo
  - fire
  - networkx
  - uncertainties
  - sympy
  - autopep8
  - typeguard
  - pip:
      - -r file:requirements.txt
