name: encomp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - scipy
  - jupyter
  - fire
  - pip:
    - -r requirements.txt
    - -r requirements-optional.txt
    - -r requirements-dev.txt
