name: encomp-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandoc
  - pip:
    - -r requirements.txt
    - -r requirements-optional.txt
    - -r requirements-dev.txt
